Use `all` in default_scope_requirements for Flows
globus/globus-sdk-python pull request #1029
Opened 2024-08-09 20:57 UTC by sirosen

Update the `default_scope_requirements` field for `FlowsClient` to
list (only) the `all` scope. This increases the capabilities of a
default-built FlowsClient to include creation of a Flow.

This appears to have been a minor oversight in the initial
`default_scope_requirements` build-out, not an intentional decision to
limit capabilities. The `all` scope is newer than
`default_scope_requirements` and is the most appropriate choice now.

2024-08-12 12:28 UTC, kurtmckee approved these changes

2024-08-12 12:49 UTC, derek-globus requested changes
I’m not 100% on whether we should be defaulting to write access. It’s a balancing act as with anything between security posture and ease of use but it has some pretty big security implications if by default any script distributed using a GlobusApp requests access to not only see your flows but also create, edit, and delete them in your name.

2024-08-12 19:13 UTC, sirosen commented
We discussed and agreed not to change this -- at least not for now.

The PR was opened under the misconception that this was an oversight, but providing read-only access to services was an intentional choice (and holds across other services where applicable, e.g. Search).

2024-08-22 02:47 UTC, sirosen commented
Given that we have revisited the topic, and now believe that `all` is best for Flows, I'm going to merge based on the prior approval. (I take Derek reopening it as implicit approval.)

2024-08-22 02:47 UTC, merged