include filter rules
globus/globus-sdk-python pull request #712
Opened 2023-03-22 20:11 UTC by aaschaer

For https://app.shortcut.com/globus/story/22583/cli-add-support-for-include-filter-rules

Actual code change is just updating a `Literal`, but with a big chunk of doc to explain the new behavior. Opening as a draft as transfer has not yet released.

2023-03-22 20:33 UTC, kurtmckee requested changes

2023-03-22 20:33 UTC, kurtmckee commented on src/globus_sdk/services/transfer/data/transfer_data.py
> +        >>> tdata.add_filter_rule(method="exclude", *.tar.gz", type="file")
```suggestion
        >>> tdata.add_filter_rule(method="exclude", "*.tgz", type="file")
        >>> tdata.add_filter_rule(method="exclude", "*.tar.gz", type="file")
```

2023-03-22 20:33 UTC, kurtmckee commented on src/globus_sdk/services/transfer/data/transfer_data.py
> +        >>> tdata.add_filter_rule(method="include", *.txt", type="file")
```suggestion
        >>> tdata.add_filter_rule(method="include", "*.txt", type="file")
```

2023-03-22 20:33 UTC, kurtmckee commented on src/globus_sdk/services/transfer/data/transfer_data.py
> +        with the `.txt` extension.
```suggestion
        with the ``.txt`` extension.
```

2023-03-22 20:33 UTC, kurtmckee commented on src/globus_sdk/services/transfer/data/transfer_data.py
>          the extensions `.tgz` or `.tar.gz`
```suggestion
        the extensions ``.tgz`` or ``.tar.gz``
```

2023-03-22 20:42 UTC, kurtmckee approved these changes

2023-03-25 19:49 UTC, sirosen approved these changes

2023-03-25 19:49 UTC, sirosen commented on tests/non-pytest/mypy-ignore-tests/transfer_data.py
> +tdata.add_filter_rule("*.tgz", method="unclude")  # type: ignore[arg-type]
Somehow, this change brings me a great deal of joy.
I know it's just picking some other invalid name, but I can't help but imagine a service supporting "unclude", whatever that means. :joy:

2023-03-29 20:30 UTC, aaschaer commented
Transfer support for this was released this morning, I'm looking into the Read the Docs build failure

2023-03-29 21:22 UTC, merged